spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Manman755_
  jpa:
    show-sql: true
websiteUrl: http://localhost:3000